#!/bin/bash
yum install ntpdate lrzsz gdb gcc openssh-clients expect unzip rsync vim man sysstat -y
/usr/sbin/ntpdate asia.pool.ntp.org && clock -w &> /dev/null
echo "# Generated by iptables-save v1.4.7 on Fri Jul  5 02:04:45 2013
*filter
:INPUT DROP [637:170375]
:FORWARD ACCEPT [0:0]
:OUTPUT DROP [4:288]
-A INPUT -s 219.237.193.145 -p tcp -m tcp --dport 22 -j ACCEPT
-A OUTPUT -d 219.237.193.145 -p tcp -m tcp --sport 22 -j ACCEPT
-A INPUT -s 192.168.1.0/24 -j ACCEPT
-A OUTPUT -d 192.168.1.0/24 -j ACCEPT
-A INPUT -s 219.237.193.145 -p icmp --icmp-type echo-request -j ACCEPT
-A OUTPUT -d 219.237.193.145 -p icmp --icmp-type echo-reply -j  ACCEPT
-A OUTPUT -p icmp --icmp-type echo-request -j ACCEPT
-A INPUT -p icmp --icmp-type echo-reply -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8884 -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 8884 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8885 -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 8885 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8886 -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 8886 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8887 -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 8887 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8888 -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 8888 -j ACCEPT
-A OUTPUT -p tcp -m multiport --dport 53,80,443 -j ACCEPT
-A INPUT -p tcp -m  multiport --sport 53,80,443 -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -d 119.161.240.224/27 -p tcp -m tcp --dport 6666 -j ACCEPT
-A INPUT -s 119.161.240.224/27 -p tcp -m  tcp --sport 6666 -j ACCEPT
-A OUTPUT -d 119.161.241.0/28 -p tcp -m tcp --dport 6666 -j ACCEPT
-A INPUT -s 119.161.241.0/28 -p tcp -m  tcp --sport 6666 -j ACCEPT
-A INPUT -p udp -m udp  -m state --state ESTABLISHED -j ACCEPT
-A OUTPUT -p udp -m udp  -m state --state NEW,ESTABLISHED -j ACCEPT
-A INPUT -s 103.10.84.24 -p tcp -m multiport --dport 10050,10051 -j ACCEPT
-A OUTPUT -d 103.10.84.24 -p tcp -m multiport --sport 10050,10051 -j ACCEPT
COMMIT" > /etc/sysconfig/iptables
/etc/init.d/iptables start
yum install glibc-2.12-1.132.el6_5.4.i686 -y
yum install libgcc-4.4.7-4.el6.i686 -y
yum install glibc-2.12-1.149.el6.i686 -y
yum install libgcc-4.4.7-11.el6.i686 -y
sed -i 's/net.ipv4.tcp_syncookies = 1/net.ipv4.tcp_syncookies = 0/g' /etc/sysctl.conf 
echo "fs.file-max=30720
net.ipv4.tcp_wmem = 4096    65536   4194304
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_rmem = 4096    65536   4194304" >> /etc/sysctl.conf
/sbin/sysctl -p
sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config 
echo "   *               soft nofile 30720
   *               hard nofile 30720" >> /etc/security/limits.conf 
mkdir /home/jzadmin/game -p
mkdir /home/jzadmin/gamebao
mkdir /home/jzadmin/software
sed -i "s/^alias/#alias/g" /root/.bashrc
