#!/bin/bash
yum install ntpdate expect ftp vim -y
yum install openssh-clients -y
/usr/sbin/ntpdate asia.pool.ntp.org && clock -w
sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
echo "   *               soft nofile 30720
   *               hard nofile 30720" >> /etc/security/limits.conf
mkdir /home/jzadmin/software -p
mkdir /home/jzadmin/mysqldata/
mkdir /home/jzadmin/backup/data_dump/logs/ -p
touch /home/jzadmin/backup/data_dump/logs/mysqlbackup.log
echo "fs.file-max = 30720
net.ipv4.tcp_rmem = 4096    524288  2740224
net.ipv4.tcp_wmem = 4096    524288  2740224
net.core.rmem_max = 1048576
net.core.wmem_max = 1048576
net.core.wmem_default = 524288
net.core.rmem_default = 524288" >> /etc/sysctl.conf
/sbin/sysctl -p
echo "# Generated by iptables-save v1.4.7 on Sat Jul  6 02:43:02 2013
*filter
:INPUT DROP [22:7042]
:FORWARD ACCEPT [0:0]
:OUTPUT DROP [0:0]
-A INPUT -s 219.237.193.145 -p tcp --dport 22 -j ACCEPT
-A OUTPUT -d 219.237.193.145 -p tcp --sport 22 -j ACCEPT
-A INPUT -s 192.168.2.0/24 -i eth1 -p tcp -m tcp -j ACCEPT
-A OUTPUT -d 192.168.2.0/24 -o eth1 -p tcp -m tcp -j ACCEPT
-A INPUT -s 192.168.2.0/24 -i eth1 -p icmp -j ACCEPT
-A OUTPUT -d 192.168.2.0/24 -o eth1 -p icmp -j ACCEPT
-A INPUT -s 219.237.193.145/26 -i eth0 -p tcp -m tcp --dport 3306 -m state --state NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -d 219.237.193.145/26 -o eth0 -p tcp -m tcp --sport 3306 -m state --state ESTABLISHED -j ACCEPT
-A OUTPUT -p icmp -m icmp --icmp-type echo-request -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type echo-reply -j ACCEPT
-A INPUT -p icmp -s 219.237.193.145 --icmp-type echo-request -j ACCEPT
-A OUTPUT -p icmp -d 219.237.193.145 --icmp-type echo-reply -j ACCEPT
-A OUTPUT -p tcp -m multiport --dport 80,53 -j ACCEPT
-A INPUT -p tcp -m  multiport --sport 80,53 -j ACCEPT
-A OUTPUT -p udp -m udp -j ACCEPT
-A INPUT -p udp -m udp  -j ACCEPT
-A INPUT -s 119.161.240.254 -p tcp --dport 10050 -j ACCEPT
-A OUTPUT -d 119.161.240.254 -p tcp --sport 10050 -j ACCEPT
-A OUTPUT -d 119.161.240.254 -p tcp --dport 10051 -j ACCEPT
-A INPUT -s 119.161.240.254 -p tcp --sport 10051 -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A OUTPUT -o lo -j ACCEPT 
COMMIT" > /etc/sysconfig/iptables 
/etc/init.d/iptables start
